//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace goshopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companys
    {
        public int rowid { get; set; }
        public string mno { get; set; }
        public string msname { get; set; }
        public string mname { get; set; }
        public Nullable<System.DateTime> date_register { get; set; }
        public string tel_company { get; set; }
        public string fax_company { get; set; }
        public string name_charge { get; set; }
        public string name_contact { get; set; }
        public string tel_contact { get; set; }
        public string adr_company { get; set; }
        public string email_company { get; set; }
        public string url_company { get; set; }
        public string remark { get; set; }
    }
}
